Repository hashicorp/consul-api-gateway, pull requests merged in 2022-09, with the labels that each got.

#336 (dark) Implement cert+key retrieval using Vault's KV API
  internal/commands/server/server.go
  internal/vault/certificates.go
  internal/vault/certificates_test.go
  internal/vault/mocks/certificates.go
  internal/vault/secrets.go
  internal/vault/secrets_test.go
Labels: pr/no-changelog, pr/run-conformance

#332 Extract binding logic into Binder
  internal/adapters/consul/sync.go
  internal/adapters/consul/sync_test.go
  internal/core/interfaces.go
  internal/envoy/handler.go
  internal/envoy/handler_test.go
  internal/envoy/middleware.go
  internal/envoy/mocks/middleware.go
  internal/envoy/sds.go
  internal/envoy/sds_test.go
  internal/k8s/reconciler/binder.go
  internal/k8s/reconciler/binder_test.go
  internal/k8s/reconciler/gateway.go
  internal/k8s/reconciler/gateway_test.go
  internal/k8s/reconciler/listener.go
  internal/k8s/reconciler/route.go
  internal/k8s/reconciler/route_test.go
  internal/k8s/reconciler/state/route.go
  internal/k8s/reconciler/utils.go
  internal/k8s/reconciler/utils_test.go
  internal/store/interfaces.go
  internal/store/memory/gateway.go
  internal/store/memory/listener.go
  internal/store/memory/store.go
  internal/store/mocks/interfaces.go
Labels: pr/no-changelog, pr/run-conformance

#337 Remove unused listener types
  .golangci.yml
  internal/k8s/reconciler/gateway.go
  internal/k8s/reconciler/gateway_test.go
  internal/k8s/reconciler/listener.go
  internal/k8s/reconciler/listener_test.go
  internal/k8s/reconciler/route.go
  internal/k8s/reconciler/utils.go
  internal/store/interfaces.go
  internal/store/mocks/interfaces.go
Labels: pr/no-changelog, pr/run-conformance

#338 Management API Stubs for Gateway endpoints
  .github/workflows/ci.yml
  go.mod
  go.sum
  internal/api/middleware/oapi.go
  internal/api/schemas/v1.yaml
  internal/api/v1/handlers.go
  internal/api/v1/handlers_test.go
  internal/api/v1/server.go
  internal/api/v1/server_test.go
  internal/api/v1/zz_generated_server.go
Labels: pr/no-changelog

#339 Add HTTPRoute stubs
  internal/api/schemas/v1.config.yaml
  internal/api/schemas/v1.yaml
  internal/api/v1/gateways.go
  internal/api/v1/gateways_test.go
  internal/api/v1/httproutes.go
  internal/api/v1/httproutes_test.go
  internal/api/v1/server.go
  internal/api/v1/server_test.go
  internal/api/v1/zz_generated_server.go
Labels: pr/no-changelog

#340 Add TCPRoute stubs
  internal/api/schemas/v1.yaml
  internal/api/v1/tcproutes.go
  internal/api/v1/tcproutes_test.go
  internal/api/v1/zz_generated_server.go
Labels: pr/no-changelog

#342 (dark) Add storage "backend" interface, in-memory implementation
  internal/store/interfaces.go
  internal/store/memory/backend.go
  internal/store/memory/backend_test.go
  internal/store/mocks/interfaces.go
  internal/store/store.go
Labels: pr/no-changelog

#344 Add stubs for gateway client
  internal/api/schemas/v1.config.yaml
  internal/api/templates/client-with-responses.tmpl
  internal/api/templates/client.tmpl
  internal/api/v1/client.go
  internal/api/v1/client_test.go
  internal/api/v1/server.go
  internal/api/v1/zz_generated.go
  internal/api/v1/zz_generated_extensions.go
  internal/api/v1/zz_generated_server.go
Labels: pr/no-changelog

#351 (dark) Include marshaling funcs when generating statuses
  .gitattributes
  internal/k8s/reconciler/status/generator.go
  internal/k8s/reconciler/status/zz_generated_status.go
  internal/k8s/reconciler/status/zz_generated_status_test.go
Labels: pr/no-changelog, pr/run-conformance

#358 Refactor binder interface to be reusable for multiple gateways
  internal/k8s/reconciler/binder.go
  internal/k8s/reconciler/binder_test.go
  internal/k8s/reconciler/gateway.go
Labels: pr/no-changelog, pr/run-conformance

#357 Move gateway + route validation up into reconcile manager
  internal/k8s/reconciler/binder_test.go
  internal/k8s/reconciler/factory.go
  internal/k8s/reconciler/gateway.go
  internal/k8s/reconciler/manager.go
  internal/k8s/reconciler/mocks/manager.go
  internal/k8s/reconciler/route.go
  internal/k8s/reconciler/route_test.go
  internal/k8s/reconciler/validator/gateway.go
  internal/k8s/reconciler/validator/gateway_test.go
  internal/k8s/reconciler/validator/route.go
  internal/k8s/reconciler/validator/route_test.go
Labels: pr/no-changelog, pr/run-conformance

#362 Update supported-features.md
  dev/docs/supported-features.md
Labels: pr/no-changelog

#364 (dark) Refactor status syncing logic out of K8sGateway + K8sGateway into StatusUpdater
  internal/k8s/reconciler/statuses.go
  internal/k8s/reconciler/statuses_test.go
Labels: pr/no-changelog, pr/run-conformance

#352 Add basic controller CLI entrypoint
  internal/api/server.go
  internal/commands/controller/command.go
  internal/commands/controller/health.go
  internal/commands/exec/exec.go
  internal/common/flags.go
  internal/consul/registration.go
  internal/consul/registration_test.go
  internal/envoy/sds.go
  main.go
Labels: pr/no-changelog

#353 VM deployment cli entrypoint
  internal/api/apiinternal/bootstrap.go
  internal/api/apiinternal/bootstrap_test.go
  internal/api/apiinternal/client.go
  internal/api/apiinternal/client_test.go
  internal/api/apiinternal/middleware.go
  internal/api/apiinternal/server.go
  internal/api/apiinternal/zz_generated.go
  internal/api/apiinternal/zz_generated_extensions.go
  internal/api/client.go
  internal/api/internal/bootstrap.go
  internal/api/schemas/internal.config.yaml
  internal/api/schemas/internal.yaml
  internal/api/server.go
  internal/commands/controller/command.go
  internal/commands/deployment/command.go
  internal/commands/exec/exec.go
  internal/common/cli.go
  internal/consul/registration.go
  internal/consul/registration_test.go
  main.go
Labels: pr/no-changelog

#365 (dark) Initial Consul backend storage implementation
  internal/store/consul_backend.go
  internal/store/consul_backend_test.go
Labels: pr/no-changelog

#359 VM initial runtime validation
  internal/api/schemas/v1.yaml
  internal/api/server.go
  internal/api/v1/client_test.go
  internal/api/v1/gateways.go
  internal/api/v1/gateways_test.go
  internal/api/v1/health_test.go
  internal/api/v1/httproutes.go
  internal/api/v1/httproutes_test.go
  internal/api/v1/middleware_test.go
  internal/api/v1/server.go
  internal/api/v1/tcproutes.go
  internal/api/v1/tcproutes_test.go
  internal/api/v1/zz_generated.go
  internal/api/v1/zz_mocks_test.go
  internal/commands/controller/command.go
  internal/common/tls.go
  internal/k8s/reconciler/validator/gateway.go
  internal/k8s/reconciler/validator/tls.go
  internal/testing/strings.go
  internal/vm/validation.go
  internal/vm/validation_test.go
Labels: pr/no-changelog

#367 (dark) Move in-memory backend into store pkg alongside Consul backend
  internal/store/memory_backend.go
  internal/store/memory_backend_test.go
Labels: pr/no-changelog, refactor

#368 Specify primary datacenter for root cert watch
  .changelog/368.txt
  internal/commands/exec/command.go
  internal/commands/exec/exec.go
  internal/commands/server/command.go
  internal/commands/server/server.go
  internal/consul/certmanager.go
  internal/k8s/builder/gateway.go
  internal/k8s/controller.go
  internal/k8s/reconciler/deployer.go
  internal/k8s/reconciler/manager.go
Labels: pr/run-conformance

#372 api: use chi/v5 everywhere
  go.mod
  go.sum
  internal/api/server.go
Labels: pr/no-changelog

#374 Update dependency to resolve GO-2022-0969
  go.mod
  go.sum
Labels: pr/no-changelog

#377 Remove ACL tokens on shutdown of Gateway
  .changelog/377.txt
  internal/commands/exec/exec.go
  internal/commands/exec/exec_test.go
Labels: pr/run-conformance

#383 Clean up before replacing old store w/ new
  internal/commands/server/command.go
  internal/commands/server/server_test.go
  internal/core/http.go
  internal/core/resolved.go
  internal/core/tcp.go
  internal/envoy/middleware.go
  internal/envoy/sds.go
  internal/k8s/reconciler/gatewayclass.go
  internal/k8s/reconciler/state/gateway.go
  internal/k8s/reconciler/state/route.go
  internal/k8s/reconciler/utils.go
  internal/k8s/reconciler/utils_test.go
  internal/k8s/reconciler/validator/route_test.go
  internal/k8s/service/resolver.go
  internal/store/interfaces.go
  internal/store/mocks/interfaces.go
  internal/store/store.go
Labels: pr/no-changelog, pr/run-conformance, refactor

#369 Replace old store w/ new store
  internal/commands/controller/command.go
  internal/commands/server/server.go
  internal/envoy/middleware.go
  internal/envoy/sds_test.go
  internal/k8s/config.go
  internal/k8s/controller.go
  internal/k8s/reconciler/binder.go
  internal/k8s/reconciler/binder_test.go
  internal/k8s/reconciler/factory.go
  internal/k8s/reconciler/gateway.go
  internal/k8s/reconciler/gateway_test.go
  internal/k8s/reconciler/manager.go
  internal/k8s/reconciler/route.go
  internal/k8s/reconciler/route_test.go
  internal/store/interfaces.go
  internal/store/memory/store.go
  internal/store/mocks/interfaces.go
  internal/store/store.go
  internal/testing/e2e/consul.go
  internal/testing/e2e/gateway.go
Labels: pr/no-changelog, pr/run-conformance, refactor

#386 Cleanup post-refactor
  internal/api/v1/gateways_test.go
  internal/api/v1/httproutes_test.go
  internal/api/v1/tcproutes_test.go
  internal/core/http.go
  internal/core/resolved.go
  internal/core/tcp.go
  internal/k8s/reconciler/binder_test.go
  internal/k8s/reconciler/converter/http.go
  internal/k8s/reconciler/converter/tcp.go
  internal/k8s/reconciler/factory.go
  internal/k8s/reconciler/gateway_test.go
  internal/k8s/reconciler/manager.go
  internal/k8s/reconciler/marshaler_test.go
  internal/k8s/reconciler/route.go
  internal/k8s/reconciler/route_test.go
  internal/k8s/reconciler/state/gateway.go
  internal/k8s/reconciler/statuses_test.go
  internal/k8s/service/resolver.go
Labels: pr/no-changelog, pr/run-conformance, refactor

#394 ci: switch to pr/conformance label
  .github/workflows/conformance_with_build.yml
Labels: pr/no-changelog, pr/conformance

#393 Update e2e tests to work on k8s 1.24
  .github/workflows/ci.yml
  internal/testing/e2e/kind.go
  internal/testing/e2e/kubernetes.go
Labels: pr/no-changelog, pr/run-conformance

#395 Run conformance tests on k8s 1.24
  .github/actions/setup-kind/action.yml
Labels: pr/no-changelog, pr/conformance
