Repository hashicorp/consul-api-gateway, pull requests merged in 2022-04, with the labels that each got.

#139 Add conformance testing workflow for GitHub Actions
  .github/workflows/conformance.yml
  .gitignore
  Dockerfile.local
  internal/testing/conformance/README.md
  internal/testing/conformance/consul-config.yaml
  internal/testing/conformance/kustomization.yaml
  internal/testing/conformance/metallb-config.yaml
Labels: pr/run-conformance

#142 Validate ReferencePolicy for cross-namespace routing, log future enforcement
  config/rbac/role.yaml
  internal/k8s/controllers/gateway_controller.go
  internal/k8s/gatewayclient/gatewayclient.go
  internal/k8s/gatewayclient/mocks/gatewayclient.go
  internal/k8s/reconciler/route.go
  internal/k8s/reconciler/route_test.go
  internal/k8s/reconciler/utils.go
  internal/k8s/reconciler/utils_test.go
Labels: pr/run-conformance

#143 Set status error message
  .changelog/143.txt
  .github/workflows/conformance.yml
  internal/k8s/reconciler/config/statuses.yaml
  internal/k8s/reconciler/route.go
  internal/k8s/reconciler/route_test.go
  internal/k8s/reconciler/utils.go
  internal/k8s/reconciler/zz_generated_status.go
  internal/k8s/reconciler/zz_generated_status_test.go
  internal/k8s/service/resolver.go
  internal/k8s/service/resolver_test.go
Labels: pr/run-conformance

#145 Enable slack webhook
  .github/workflows/conformance.yml
Labels: pr/run-conformance

#161 Specify explicit type config for Envoy bootstrap filters
  internal/envoy/manager.go
  internal/envoy/testdata/basic.golden.json
  internal/envoy/testdata/empty.golden.json
  internal/envoy/testdata/sds.golden.json
  internal/envoy/testdata/tls.golden.json
Labels: pr/run-conformance

#168 0.2.0 Release
  .release/ci.hcl
  CHANGELOG.md
  README.md
  config/deployment/deployment.yaml
  dev/docs/example-setup.md
  dev/docs/supported-features.md
  internal/k8s/builder/testdata/clusterip.deployment.golden.yaml
  internal/k8s/builder/testdata/loadbalancer.deployment.golden.yaml
  internal/k8s/builder/testdata/static-mapping.deployment.golden.yaml
  internal/k8s/builder/testdata/tls-cert.deployment.golden.yaml
  internal/version/version.go
Labels: pr/no-changelog

#169 Add promote-dev-docker step to ci.hcl
  .release/ci.hcl
Labels: pr/no-changelog

#170 Add promote-dev-docker step to ci.hcl (#169)
  .release/ci.hcl
Labels: pr/no-changelog

#171 Add dev_tags section for build.yml
  .github/workflows/build.yml
Labels: pr/no-changelog

#175 Add context to TCPRouteController initialization
  internal/k8s/controller.go
Labels: pr/no-changelog

#176 0.2.x nil pointer fix
  internal/k8s/controller.go
Labels: pr/no-changelog

#167 ci: bump Go version to 1.18
  .changelog/167.txt
  .github/workflows/ci.yml
  .github/workflows/conformance.yml
  go.mod
  go.sum
  internal/commands/server/k8s_e2e_test.go
Labels: pr/run-conformance

#187 Bug: LoadBalancers - Use Hostnames in addition to IP
  .changelog/187.txt
  internal/k8s/reconciler/gateway.go
  internal/k8s/reconciler/gateway_test.go
Labels: type/bug, pr/run-conformance, backport-0.2.x
