Repository hashicorp/consul-api-gateway, pull requests merged in 2022-08, with the labels that each got.

#293 referencepolicy: finish backwards compatibility support and tests
  internal/commands/server/k8s_e2e_test.go
  internal/k8s/controllers/gateway_controller_test.go
  internal/k8s/controllers/tcp_route_controller.go
  internal/k8s/gatewayclient/gatewayclient.go
Labels: pr/no-changelog

#297 ci: remove GitHub Container Registry publishing
  .github/workflows/docker.yml
Labels: pr/no-changelog

#295 Implement cert+key retrieval using Vault's PKI API
  go.mod
  go.sum
  internal/commands/server/command.go
  internal/commands/server/server.go
  internal/envoy/secrets.go
  internal/k8s/certificates.go
  internal/k8s/reconciler/listener.go
  internal/k8s/utils/secrets.go
  internal/testing/e2e/gateway.go
  internal/vault/certificates.go
  internal/vault/certificates_test.go
  internal/vault/mocks/certificates.go
  internal/vault/secrets.go
  internal/vault/secrets_test.go
Labels: pr/no-changelog

#302 TLS Watch and Rotate
  internal/envoy/mocks/secrets.go
  internal/envoy/sds.go
  internal/envoy/secrets.go
  internal/envoy/secrets_test.go
Labels: pr/no-changelog

#303 ci: update Consul versions in test matrices, bump consul-k8s to v0.47.1
  .github/workflows/build.yml
  .github/workflows/ci.yml
  .github/workflows/conformance.yml
  .github/workflows/conformance_with_build.yml
  internal/testing/conformance/consul-config.yaml
Labels: pr/no-changelog, pr/run-conformance

#308 Fix intention syncing CAS index
  .changelog/308.txt
  internal/commands/server/k8s_e2e_test.go
  internal/consul/intentions.go
Labels: pr/run-conformance

#307 ci: add Consul v1.13 and 1.14-dev edge builds to test matrices
  .github/workflows/ci.yml
  .github/workflows/conformance.yml
  .github/workflows/conformance_with_build.yml
Labels: pr/no-changelog, pr/run-conformance

#310 Bump Consul API Gateway version in supported-features.md on pre-relea…
  .github/workflows/prepare_release.yml
Labels: pr/no-changelog

#309 Prepare for release of v0.4.0
  CHANGELOG.md
  README.md
  config/deployment/deployment.yaml
  dev/docs/example-setup.md
  dev/docs/supported-features.md
Labels: pr/no-changelog

#313 Remove logic for handling unsupported UDPRoute + TLSRoute
  internal/core/resolved.go
  internal/k8s/reconciler/listener_test.go
  internal/k8s/reconciler/manager.go
  internal/k8s/reconciler/manager_test.go
  internal/k8s/reconciler/mocks/manager.go
  internal/k8s/reconciler/route.go
  internal/k8s/reconciler/route_test.go
  internal/k8s/reconciler/tls_route.go
  internal/k8s/reconciler/tls_route_test.go
  internal/k8s/reconciler/udp_route.go
  internal/k8s/reconciler/udp_route_test.go
  internal/k8s/service/rule.go
Labels: pr/no-changelog

#311 Bump version to next minor release
  internal/k8s/builder/testdata/clusterip.deployment.golden.yaml
  internal/k8s/builder/testdata/loadbalancer.deployment.golden.yaml
  internal/k8s/builder/testdata/static-mapping.deployment.golden.yaml
  internal/k8s/builder/testdata/tls-cert.deployment.golden.yaml
  internal/version/version.go
Labels: pr/no-changelog

#312 Bump version to next patch release
  internal/k8s/builder/testdata/clusterip.deployment.golden.yaml
  internal/k8s/builder/testdata/loadbalancer.deployment.golden.yaml
  internal/k8s/builder/testdata/static-mapping.deployment.golden.yaml
  internal/k8s/builder/testdata/tls-cert.deployment.golden.yaml
  internal/version/version.go
Labels: pr/no-changelog

#314 Split error + status generation into separate subpackages of reconciler
  internal/commands/server/k8s_e2e_test.go
  internal/k8s/reconciler/errors/errors.yaml
  internal/k8s/reconciler/errors/generator.go
  internal/k8s/reconciler/errors/zz_generated_errors.go
  internal/k8s/reconciler/errors/zz_generated_errors_test.go
  internal/k8s/reconciler/gateway.go
  internal/k8s/reconciler/gateway_test.go
  internal/k8s/reconciler/gatewayclass.go
  internal/k8s/reconciler/gatewayclass_test.go
  internal/k8s/reconciler/listener.go
  internal/k8s/reconciler/listener_test.go
  internal/k8s/reconciler/route.go
  internal/k8s/reconciler/route_test.go
  internal/k8s/reconciler/status/generator.go
  internal/k8s/reconciler/status/statuses.yaml
  internal/k8s/reconciler/status/zz_generated_status.go
  internal/k8s/reconciler/status/zz_generated_status_test.go
Labels: pr/no-changelog

#316 Update API Gateway pins for nightly conformance runs
  .github/workflows/conformance.yml
Labels: pr/no-changelog

#315 Refactor deploy logic out of K8sGateway
  internal/k8s/reconciler/deployer.go
  internal/k8s/reconciler/gateway.go
  internal/k8s/reconciler/gateway_test.go
  internal/k8s/reconciler/manager.go
  pkg/apis/v1alpha1/types.go
Labels: pr/no-changelog, pr/run-conformance

#317 Refactor K8sGateway state into serializable struct
  internal/k8s/reconciler/common/utils.go
  internal/k8s/reconciler/gateway.go
  internal/k8s/reconciler/gateway_test.go
  internal/k8s/reconciler/listener.go
  internal/k8s/reconciler/listener_test.go
  internal/k8s/reconciler/route.go
  internal/k8s/reconciler/state/gateway.go
  internal/k8s/reconciler/status/equality.go
  internal/k8s/reconciler/tls.go
Labels: pr/no-changelog, pr/run-conformance

#320 Refactor K8sRoute state into serializable struct
  internal/k8s/reconciler/gateway_test.go
  internal/k8s/reconciler/http_route.go
  internal/k8s/reconciler/http_route_test.go
  internal/k8s/reconciler/manager.go
  internal/k8s/reconciler/manager_test.go
  internal/k8s/reconciler/route.go
  internal/k8s/reconciler/route_test.go
  internal/k8s/reconciler/state/route.go
  internal/k8s/reconciler/status/route.go
  internal/k8s/reconciler/status/route_test.go
  internal/k8s/reconciler/tcp_route.go
  internal/store/interfaces.go
  internal/store/memory/store.go
  internal/store/mocks/interfaces.go
Labels: pr/no-changelog, pr/run-conformance

#322 Update crypto package to fix GO-2021-0356
  go.mod
  go.sum
Labels: pr/no-changelog

#321 Introduce Factory for creating Gateways + Routes
  internal/k8s/reconciler/factory.go
  internal/k8s/reconciler/gateway.go
  internal/k8s/reconciler/gateway_test.go
  internal/k8s/reconciler/listener_test.go
  internal/k8s/reconciler/manager.go
  internal/k8s/reconciler/route.go
  internal/k8s/reconciler/route_test.go
  internal/k8s/reconciler/utils_test.go
  internal/k8s/service/mocks/resolver.go
  internal/k8s/service/resolver.go
Labels: pr/no-changelog, pr/run-conformance

#323 Extract validation logic for Gateway into GatewayValidator
  internal/k8s/reconciler/factory.go
  internal/k8s/reconciler/gateway.go
  internal/k8s/reconciler/gateway_test.go
  internal/k8s/reconciler/listener.go
  internal/k8s/reconciler/listener_test.go
  internal/k8s/reconciler/route_test.go
  internal/k8s/reconciler/utils.go
  internal/k8s/reconciler/utils_test.go
  internal/k8s/reconciler/validator/gateway.go
  internal/k8s/reconciler/validator/gateway_test.go
  internal/k8s/reconciler/validator/tls.go
  internal/k8s/reconciler/validator/utils.go
  internal/k8s/reconciler/validator/utils_test.go
  internal/store/memory/listener.go
Labels: pr/no-changelog, pr/run-conformance

#330 Extract validation logic for Route into RouteValidator
  internal/k8s/reconciler/route.go
  internal/k8s/reconciler/route_test.go
  internal/k8s/reconciler/utils.go
  internal/k8s/reconciler/utils_test.go
  internal/k8s/reconciler/validator/gateway.go
  internal/k8s/reconciler/validator/gateway_test.go
  internal/k8s/reconciler/validator/route.go
  internal/k8s/reconciler/validator/route_test.go
  internal/k8s/reconciler/validator/utils.go
  internal/k8s/reconciler/validator/utils_test.go
Labels: pr/no-changelog, pr/run-conformance

#331 Extract conversion logic for Route into xRouteConverter
  internal/k8s/reconciler/converter/http.go
  internal/k8s/reconciler/converter/http_test.go
  internal/k8s/reconciler/converter/tcp.go
  internal/k8s/reconciler/listener.go
  internal/k8s/reconciler/route.go
  internal/k8s/reconciler/route_test.go
  internal/k8s/reconciler/tcp_route_test.go
  internal/store/interfaces.go
  internal/store/memory/listener.go
  internal/store/mocks/interfaces.go
Labels: pr/no-changelog, pr/run-conformance
